#!/bin/bash
### BEGIN INIT INFO
# Provides:          /root/kazoo_proxy/app.js
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: forever running /root/kazoo_proxy/app.js
# Description:       /root/kazoo_proxy/app.js
### END INIT INFO
#
# initd a node app
# Based on a script posted by https://gist.github.com/jinze at https://gist.github.com/3748766
#

# Source function library.
. /lib/lsb/init-functions

PORTS="8001 8002 8003 8004"


command="pm2"
nodeApp="/root/applog-dev/index.js"
appID="mobilelogs"

start() {
  PATH=/usr/local/bin:$PATH
  export NODE_ENV=production

	for PORT in $PORTS; do
    echo "Starting $nodeApp on port $PORT"
  
  
  pidFile="/var/run/applog_$PORT.pid"
  logFile="/var/log/applog_$PORT.log"
	
  # Notice that we change the PATH because on reboot
   # the PATH does not include the path to node.
   # Launching forever with a full path
   # does not work unless we set the PATH.
	
   
   PORT=$PORT $command -n $appID start $nodeApp -f --watch
   if [ $? -ne 0 ]; then
      echo "Running $nodeApp on port $PORT failed"
   fi 

   done

   
}

restart() {
	echo -n "Restarting $nodeApp"
	$command restart $appID
	RETVAL=$?
}

stop() {
	echo -n "Shutting down $nodeApp"
   $command stop $appID
   RETVAL=$?
}

status() {
   echo -n "Status $nodeApp"
   $command list
   RETVAL=$?
}

case "$1" in
   start)
        start
        ;;
    stop)
        stop
        ;;
   status)
        status
       ;;
   restart)
   	restart
        ;;
	*)
       echo "Usage:  {start|stop|status|restart}"
       exit 1
        ;;
esac
exit $RETVAL


